In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [4]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


In [5]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [6]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


In [7]:
import numpy as np

# 1️⃣ Create a 3×3 array with random numbers and print its shape
arr_random = np.random.randint(1, 100, size=(3, 3))
print("3x3 Random Array:\n", arr_random)
print("Shape:", arr_random.shape)

print("-" * 40)

# 2️⃣ Convert an array of floats into integers
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(int)
print("Float Array:", float_arr)
print("Integer Array:", int_arr)

print("-" * 40)

# 3️⃣ Extract even numbers using fancy indexing
arr = np.array([1, 2, 3, 4, 5, 6])
even_numbers = arr[arr % 2 == 0]
print("Even Numbers:", even_numbers)

print("-" * 40)

# 4️⃣ Reshape a 1D array of size 9 into a 3×3 matrix
arr_1d = np.arange(1, 10)
matrix_3x3 = arr_1d.reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)

print("-" * 40)

# 5️⃣ Filter numbers greater than 50 using boolean masking
arr_filter = np.array([10, 45, 60, 80, 25, 90])
filtered_numbers = arr_filter[arr_filter > 50]
print("Numbers greater than 50:", filtered_numbers)


3x3 Random Array:
 [[44 79 95]
 [ 2 29 50]
 [88 27  7]]
Shape: (3, 3)
----------------------------------------
Float Array: [1.1 2.2 3.3]
Integer Array: [1 2 3]
----------------------------------------
Even Numbers: [2 4 6]
----------------------------------------
3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------
Numbers greater than 50: [60 80 90]
