In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [3]:
# Accessing an element
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6

6


In [4]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [5]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [6]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [7]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [8]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [9]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
